[BOT]
; Your Discord Bot Token Here
token = 
; Log Level: DEBUG, INFO, WARNING, ERROR, CRITICAL
LOG_LEVEL = INFO
; Path to your Google Cloud Platform Credentials JSON file
GCP_CREDENTIALS = key.json
; after setup config file, please rename config_example.ini to config.ini
